name: Maven Build & Auto-Approve PR

on:
  pull_request:
    branches:
      - master  # based on your target branch

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

  approve:
    needs: build  # Runs only if the build job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
